#? file: https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]
prepend_keymap = [
  { on = "?", run = "help", desc = "Open help" },
  { on = "!", run = 'shell "$SHELL" --block', desc = "Open shell here" },
]

#? https://yazi-rs.github.io/docs/tips#close-input-by-esc
[input]
prepend_keymap = [{ on = "<Esc>", run = "close", desc = "Cancel input" }]

[help]
append_keymap = [{ on = "/", run = "filter", desc = "Filter help items" }]
